version: '3'
services:
  jupyter:
    build: .
    environment:
      - JUPYTER_TOKEN=${JUPYTER_TOKEN}
    ports:
      - "8888:8888"
    volumes:
      - .:/master-thesis-project
    env_file:
      - .env
